// Supabase Configuration
export const SUPABASE_CONFIG = {
  URL: 'https://jrbavagemjicwnltwval.supabase.co',
  ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyYmF2YWdlbWppY3dubHR3dmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDg0NzgsImV4cCI6MjA4NzQyNDQ3OH0.eY3c9suYSHeDrro8yCcqh-6KMul2GEHSNs2BndTo2N4',
  SERVICE_ROLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyYmF2YWdlbWppY3dubHR3dmFsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTg0ODQ3OCwiZXhwIjoyMDg3NDI0NDc4fQ.BWc34a8PK-W9y2xu1A0ppb-32wIpLp1tADl5Bv5t9Uc'
}

// Export individual values for convenience
export const SUPABASE_URL = SUPABASE_CONFIG.URL
export const SUPABASE_ANON_KEY = SUPABASE_CONFIG.ANON_KEY
export const SUPABASE_SERVICE_ROLE_KEY = SUPABASE_CONFIG.SERVICE_ROLE_KEY
